spring:
  application:
    name: service
server:
  port: 8765
eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      my-metadata: 我自定义的元数据